"""Dataset manifold resolution and symlink mapping cell generator.

Discovers attached manifolds on Kaggle/Colab, constructs annual Forex universes,
resolves aliases, and mounts datasets into LemGendaryDatasets.
"""

from typing import Any

from ..registry import ModelNotebookMeta
from .base import make_code_cell


def build_symlink_cell(meta: ModelNotebookMeta, target: str = "kaggle") -> dict[str, Any]:
    """Build the dataset manifold resolution and symlink mapping code cell."""
    if target == "kaggle":
        source = [
            "import os, re\n",
            f"model_key = '{meta.model_key}'\n",
            "target_dir = '/kaggle/working/LemGendaryDatasets'\n",
            "os.makedirs(target_dir, exist_ok=True)\n",
            "\n",
            "print(f'[DATA] Resolving manifolds for {model_key}...')\n",
            "found = []\n",
            f"keys = {meta.ds_keys_repr}\n",
            "\n",
            f"if {meta.is_forex} or any('forex' in k for k in keys):\n",
            "    forex_composite_dir = os.path.join(target_dir, 'LemGendizedForexUniverseLarge')\n",
            "    os.makedirs(forex_composite_dir, exist_ok=True)\n",
            "    forex_years_found = {}\n",
            "    if os.path.exists('/kaggle/input'):\n",
            "        try:\n",
            "            for root_dir, dirs, files in os.walk('/kaggle/input'):\n",
            "                for f in files:\n",
            "                    if f.startswith('ForexUniverse20') and f.endswith('.parquet'):\n",
            "                        cand = os.path.join(root_dir, f)\n",
            "                        for y in range(2019, 2027):\n",
            "                            if str(y) in f:\n",
            "                                forex_years_found[f'ForexUniverse{y}.parquet'] = cand\n",
            "                                break\n",
            "                dirs[:] = [d for d in dirs if d.lower() not in ['models', 'checkpoints', 'weights', 'images', 'targets']]\n",
            "                for d in dirs:\n",
            "                    if (d.startswith('ForexUniverse20') or 'forexuniverse20' in d.lower()) and not d.endswith('.zip'):\n",
            "                        cand = os.path.join(root_dir, d)\n",
            "                        try:\n",
            "                            subs = os.listdir(cand)\n",
            "                            for sub in subs:\n",
            "                                if sub.startswith('ForexUniverse20') and sub.endswith('.parquet'):\n",
            "                                    for y in range(2019, 2027):\n",
            "                                        if str(y) in sub:\n",
            "                                            forex_years_found[f'ForexUniverse{y}.parquet'] = os.path.join(cand, sub)\n",
            "                                            break\n",
            "                            if any(p in subs for p in ['EURUSD', 'USDJPY', 'GBPUSD', 'AUDUSD', 'XAUUSD', 'category.txt', 'dataset_info.yaml', 'classes.txt']):\n",
            "                                yr_clean = d\n",
            "                                for y in range(2019, 2027):\n",
            "                                    if str(y) in d:\n",
            "                                        yr_clean = f'ForexUniverse{y}'\n",
            "                                        break\n",
            "                                if f'{yr_clean}.parquet' not in forex_years_found:\n",
            "                                    forex_years_found[yr_clean] = cand\n",
            "                        except OSError:\n",
            "                            pass\n",
            "        except Exception as e:\n",
            "            print(f'[REMEDY] Forex manifold scan notice: {e}')\n",
            "    \n",
            "    if forex_years_found:\n",
            "        print(f'[FOREX] Assembling {len(forex_years_found)} annual manifolds into {forex_composite_dir}...')\n",
            "        for yr_name, yr_path in sorted(forex_years_found.items()):\n",
            "            c_link = os.path.join(forex_composite_dir, yr_name)\n",
            "            if not os.path.exists(c_link):\n",
            "                try:\n",
            "                    os.symlink(yr_path, c_link)\n",
            "                    print(f'   -> [OK] [COMPOSITE] {yr_name} -> {yr_path}')\n",
            "                except Exception as e:\n",
            "                    print(f'[REMEDY] Symlink error for {yr_name}: {e}')\n",
            "            flat_link = os.path.join(target_dir, yr_name)\n",
            "            if not os.path.exists(flat_link):\n",
            "                try:\n",
            "                    os.symlink(yr_path, flat_link)\n",
            "                except Exception:\n",
            "                    pass\n",
            "            meta_source_dir = os.path.dirname(yr_path) if os.path.isfile(yr_path) else yr_path\n",
            "            for meta in ['dataset_info.yaml', 'category.txt', 'classes.txt', 'README.md']:\n",
            "                m_src = os.path.join(meta_source_dir, meta)\n",
            "                m_dst = os.path.join(forex_composite_dir, meta)\n",
            "                if os.path.exists(m_src) and not os.path.exists(m_dst):\n",
            "                    try:\n",
            "                        os.symlink(m_src, m_dst)\n",
            "                    except Exception:\n",
            "                        pass\n",
            "        link_alias = os.path.join(target_dir, 'forex')\n",
            "        if not os.path.exists(link_alias):\n",
            "            try:\n",
            "                os.symlink(forex_composite_dir, link_alias)\n",
            "            except Exception:\n",
            "                pass\n",
            "        print(f'[OK] [FOREX] Assembly complete: {len(forex_years_found)} annual manifolds operational for Walk-Forward Curriculum.')\n",
            "        found.append(forex_composite_dir)\n",
            "\n",
            "def _scan_kaggle_inputs(root='/kaggle/input', max_depth=6):\n",
            "    if not os.path.isdir(root):\n",
            "        return []\n",
            "    results = []\n",
            "    seen = set()\n",
            "    _MANIFOLD_SUBDIRS = {'images', 'targets', 'masks', 'forex', 'train', 'val', 'test', 'splits'}\n",
            "    _MANIFOLD_META = {'dataset_info.yaml', 'category.txt', 'classes.txt', 'README.md'}\n",
            "    def _looks_like_manifold(p):\n",
            "        if not os.path.isdir(p):\n",
            "            return False\n",
            "        try:\n",
            "            names = os.listdir(p)\n",
            "        except OSError:\n",
            "            return False\n",
            "        if any(f.endswith('.parquet') for f in names):\n",
            "            return True\n",
            "        if any(f in names for f in _MANIFOLD_META):\n",
            "            return True\n",
            "        for n in names:\n",
            "            full = os.path.join(p, n)\n",
            "            if os.path.isdir(full) and n.lower() in _MANIFOLD_SUBDIRS:\n",
            "                return True\n",
            "        return False\n",
            "    def _walk(start, depth=0):\n",
            "        if depth > max_depth or not os.path.isdir(start):\n",
            "            return\n",
            "        if _looks_like_manifold(start):\n",
            "            real = os.path.realpath(start)\n",
            "            if real not in seen:\n",
            "                seen.add(real)\n",
            "                results.append(start)\n",
            "            return\n",
            "        try:\n",
            "            children = os.listdir(start)\n",
            "        except OSError:\n",
            "            return\n",
            "        for child in children:\n",
            "            _walk(os.path.join(start, child), depth + 1)\n",
            "    for top in os.listdir(root):\n",
            "        top_path = os.path.join(root, top)\n",
            "        if not os.path.isdir(top_path):\n",
            "            continue\n",
            "        if top == 'datasets':\n",
            "            try: owners = os.listdir(top_path)\n",
            "            except OSError: continue\n",
            "            for owner in owners:\n",
            "                owner_path = os.path.join(top_path, owner)\n",
            "                if not os.path.isdir(owner_path): continue\n",
            "                try: slugs = os.listdir(owner_path)\n",
            "                except OSError: continue\n",
            "                for slug in slugs:\n",
            "                    slug_path = os.path.join(owner_path, slug)\n",
            "                    if os.path.isdir(slug_path):\n",
            "                        _walk(slug_path, depth=0)\n",
            "        elif top == 'models':\n",
            "            continue\n",
            "        else:\n",
            "            _walk(top_path, depth=0)\n",
            "    return results\n",
            "\n",
            "if os.path.exists('/kaggle/input'):\n",
            "    attached = _scan_kaggle_inputs()\n",
            "    if attached:\n",
            "        print(f'[PRE-FLIGHT] Discovered {len(attached)} attached manifold(s) in /kaggle/input:')\n",
            "        for cand in attached:\n",
            "            print(f'   -> {cand}')\n",
            "        for cand in attached:\n",
            "            bname = os.path.basename(cand)\n",
            "            aliases = {bname, bname.lower()}\n",
            "            stripped = re.sub(r'^LemGendized', '', bname, flags=re.IGNORECASE)\n",
            "            if stripped != bname:\n",
            "                aliases.add(stripped)\n",
            "                aliases.add(stripped.lower())\n",
            "                for suf in ('Large', 'Medium', 'Small'):\n",
            "                    if stripped.endswith(suf):\n",
            "                        stem = stripped[:-len(suf)]\n",
            "                        aliases.add(stem)\n",
            "                        aliases.add(stem.lower())\n",
            "            for alias in aliases:\n",
            "                if not alias: continue\n",
            "                link_name = os.path.join(target_dir, alias)\n",
            "                if os.path.exists(link_name): continue\n",
            "                try:\n",
            "                    os.symlink(cand, link_name)\n",
            "                    print(f'   -> [OK] [LINKED] {alias} -> {cand}')\n",
            "                except OSError as e:\n",
            "                    print(f'   -> [WARN] Symlink failed for {alias}: {e}')\n",
            "            found.append(cand)\n",
            "\n",
            "if not found:\n",
            "    raise RuntimeError(\n",
            "        f'[ABORT] Nothing attached in /kaggle/input for {model_key}. '\n",
            "        f'Attach the dataset via the Kaggle sidebar (Add Input -> Your Datasets) '\n",
            "        f'and re-run from the top.'\n",
            "    )\n",
            "\n",
            "print(f'[OK] [DATA] {len(found)} manifold symlink(s) ready in {target_dir}.')\n",
        ]
    else:
        source = [
            "import os, subprocess, shutil, sys, re\n",
            f"model_key = '{meta.model_key}'\n",
            f"kaggle_repo = '{meta.clean_kaggle_repo}'\n",
            f"primary_manifold = '{meta.primary_manifold}'\n",
            "target_dir = '/content/LemGendaryDatasets'\n",
            "os.makedirs(target_dir, exist_ok=True)\n",
            "dest_path = os.path.join(target_dir, primary_manifold)\n",
            "\n",
            "print(f'[DATA] Resolving dataset manifold for {model_key}...')\n",
            "print(f'[DATA] Target manifold: {primary_manifold} | Kaggle source: {kaggle_repo}')\n",
            "\n",
            "def _scan_kaggle_inputs(root='/kaggle/input', max_depth=6):\n",
            "    if not os.path.isdir(root):\n",
            "        return []\n",
            "    results = []\n",
            "    seen = set()\n",
            "    _MANIFOLD_SUBDIRS = {'images', 'targets', 'masks', 'forex', 'train', 'val', 'test', 'splits'}\n",
            "    _MANIFOLD_META = {'dataset_info.yaml', 'category.txt', 'classes.txt', 'README.md'}\n",
            "    def _looks_like_manifold(p):\n",
            "        if not os.path.isdir(p):\n",
            "            return False\n",
            "        try:\n",
            "            names = os.listdir(p)\n",
            "        except OSError:\n",
            "            return False\n",
            "        if any(f.endswith('.parquet') for f in names):\n",
            "            return True\n",
            "        if any(f in names for f in _MANIFOLD_META):\n",
            "            return True\n",
            "        for n in names:\n",
            "            full = os.path.join(p, n)\n",
            "            if os.path.isdir(full) and n.lower() in _MANIFOLD_SUBDIRS:\n",
            "                return True\n",
            "        return False\n",
            "    def _walk(start, depth=0):\n",
            "        if depth > max_depth or not os.path.isdir(start):\n",
            "            return\n",
            "        if _looks_like_manifold(start):\n",
            "            real = os.path.realpath(start)\n",
            "            if real not in seen:\n",
            "                seen.add(real)\n",
            "                results.append(start)\n",
            "            return\n",
            "        try:\n",
            "            children = os.listdir(start)\n",
            "        except OSError:\n",
            "            return\n",
            "        for child in children:\n",
            "            _walk(os.path.join(start, child), depth + 1)\n",
            "    for top in os.listdir(root):\n",
            "        top_path = os.path.join(root, top)\n",
            "        if not os.path.isdir(top_path):\n",
            "            continue\n",
            "        if top == 'datasets':\n",
            "            try: owners = os.listdir(top_path)\n",
            "            except OSError: continue\n",
            "            for owner in owners:\n",
            "                owner_path = os.path.join(top_path, owner)\n",
            "                if not os.path.isdir(owner_path): continue\n",
            "                try: slugs = os.listdir(owner_path)\n",
            "                except OSError: continue\n",
            "                for slug in slugs:\n",
            "                    slug_path = os.path.join(owner_path, slug)\n",
            "                    if os.path.isdir(slug_path):\n",
            "                        _walk(slug_path, depth=0)\n",
            "        elif top == 'models':\n",
            "            continue\n",
            "        else:\n",
            "            _walk(top_path, depth=0)\n",
            "    return results\n",
            "\n",
            "_kaggle_inputs = _scan_kaggle_inputs()\n",
            "if _kaggle_inputs:\n",
            "    print(f'[PRE-FLIGHT] Discovered {len(_kaggle_inputs)} attached manifold(s) in /kaggle/input.')\n",
            "    for cand in _kaggle_inputs:\n",
            "        bname = os.path.basename(cand)\n",
            "        aliases = {bname, bname.lower()}\n",
            "        stripped = re.sub(r'^LemGendized', '', bname, flags=re.IGNORECASE)\n",
            "        if stripped != bname:\n",
            "            aliases.add(stripped)\n",
            "            aliases.add(stripped.lower())\n",
            "            for suf in ('Large', 'Medium', 'Small'):\n",
            "                if stripped.endswith(suf):\n",
            "                    stem = stripped[:-len(suf)]\n",
            "                    aliases.add(stem)\n",
            "                    aliases.add(stem.lower())\n",
            "        for alias in aliases:\n",
            "            if not alias: continue\n",
            "            dst = os.path.join(target_dir, alias)\n",
            "            if os.path.exists(dst): continue\n",
            "            try:\n",
            "                os.symlink(cand, dst)\n",
            "                print(f'   -> [OK] [PRE-FLIGHT] {alias} -> {cand}')\n",
            "            except OSError as e:\n",
            "                print(f'   -> [WARN] Symlink skipped for {alias}: {e}')\n",
            "\n",
            "is_ready = os.path.exists(dest_path) and (\n",
            "    os.path.exists(os.path.join(dest_path, 'images')) or\n",
            "    os.path.exists(os.path.join(dest_path, 'targets')) or\n",
            "    any(f.endswith('.parquet') or f.endswith('.csv') or f.endswith('.json') for f in os.listdir(dest_path))\n",
            ")\n",
            "\n",
            "if is_ready:\n",
            "    print(f'[OK] [DATA] Manifold already available at {dest_path} — download skipped.')\n",
            "\n",
            "if not is_ready:\n",
            "    os.makedirs(dest_path, exist_ok=True)\n",
            "    download_ok = False\n",
            f"    _no_download = {meta.no_download}\n",
            "    if os.path.exists('/content/drive/MyDrive'):\n",
            "        print('[FALLBACK] Checking Google Drive for manifold...')\n",
            "        drive_cands = [\n",
            "            f'/content/drive/MyDrive/LemGendaryDatasets/{primary_manifold}',\n",
            "            f'/content/drive/MyDrive/{primary_manifold}',\n",
            "            f'/content/drive/MyDrive/LemGendaryDatasets/{primary_manifold.replace(\"Large\", \"\")}',\n",
            "        ]\n",
            "        for cand in drive_cands:\n",
            "            if os.path.exists(cand):\n",
            "                try:\n",
            "                    os.symlink(cand, dest_path)\n",
            "                    print(f'[OK] Symlinked from Google Drive: {cand} -> {dest_path}')\n",
            "                    download_ok = True\n",
            "                    break\n",
            "                except Exception:\n",
            "                    pass\n",
            "\n",
            "    if not download_ok and kaggle_repo and not _no_download:\n",
            "        try:\n",
            "            print(f'[KAGGLE CLI] Downloading {kaggle_repo} into {dest_path}...')\n",
            "            res = subprocess.run(\n",
            "                ['kaggle', 'datasets', 'download', '-d', kaggle_repo, '-p', dest_path, '--unzip'],\n",
            "                capture_output=True, text=True\n",
            "            )\n",
            "            if res.returncode == 0:\n",
            "                print(f'[OK] [KAGGLE CLI] Successfully downloaded and extracted {kaggle_repo}')\n",
            "                download_ok = True\n",
            "            else:\n",
            "                print(f'[WARNING] Kaggle CLI download returned code {res.returncode}: {res.stderr.strip()[:200]}')\n",
            "        except Exception as e:\n",
            "            print(f'[WARNING] Kaggle CLI download error: {e}')\n",
            "        \n",
            "        if not download_ok:\n",
            "            try:\n",
            "                print('[KAGGLEHUB] Attempting download via kagglehub...')\n",
            "                subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', 'kagglehub'], check=False)\n",
            "                import kagglehub\n",
            "                hub_path = kagglehub.dataset_download(kaggle_repo)\n",
            "                print(f'[OK] [KAGGLEHUB] Downloaded to {hub_path}')\n",
            "                for item in os.listdir(hub_path):\n",
            "                    s = os.path.join(hub_path, item)\n",
            "                    d = os.path.join(dest_path, item)\n",
            "                    if not os.path.exists(d):\n",
            "                        try: os.symlink(s, d)\n",
            "                        except Exception:\n",
            "                            if os.path.isdir(s): shutil.copytree(s, d)\n",
            "                            else: shutil.copy2(s, d)\n",
            "                download_ok = True\n",
            "            except Exception as e:\n",
            "                print(f'[WARNING] kagglehub download error: {e}')\n",
            "    \n",
            "    if not download_ok and _no_download:\n",
            "        raise RuntimeError(\n",
            "            f'[ABORT] Dataset not found in /kaggle/input or /content/drive, '\n",
            "            f'and notebook_no_download=True. Attach the dataset (Kaggle: sidebar; '\n",
            "            f'Colab: mount Google Drive) and re-run from the top.'\n",
            "        )\n",
            "\n",
            "if os.path.exists(dest_path):\n",
            "    print(f'[OK] Manifold materialized at: {dest_path}')\n",
            f"    aliases = [primary_manifold.lower(), model_key.lower(), model_key.replace('_', '-'), model_key.replace('_', '')]\n",
            f"    if {meta.is_forex}:\n",
            "        aliases.extend(['forex', 'lemgendizedforexuniverselarge'])\n",
            "    for alias in set(aliases):\n",
            "        a_path = os.path.join(target_dir, alias)\n",
            "        if not os.path.exists(a_path):\n",
            "            try: os.symlink(dest_path, a_path)\n",
            "            except Exception: pass\n",
            f"    if {meta.is_forex}:\n",
            "        forex_composite_dir = os.path.join(target_dir, 'LemGendizedForexUniverseLarge')\n",
            "        os.makedirs(forex_composite_dir, exist_ok=True)\n",
            "        for item in os.listdir(dest_path):\n",
            "            if item.startswith('ForexUniverse20') and item.endswith('.parquet'):\n",
            "                flat = os.path.join(target_dir, item)\n",
            "                if not os.path.exists(flat):\n",
            "                    try: os.symlink(os.path.join(dest_path, item), flat)\n",
            "                    except Exception: pass\n",
            "        link_alias = os.path.join(target_dir, 'forex')\n",
            "        if not os.path.exists(link_alias):\n",
            "            try: os.symlink(dest_path, link_alias)\n",
            "            except Exception: pass\n",
            "else:\n",
            "    print(f'[ERROR] Could not resolve dataset manifold for {model_key}!')\n",
        ]

    return make_code_cell(source)
