"""Dependency installation and hardware acceleration probing cell generator.

Probes CUDA / ROCm / CPU hardware accelerators and installs package manifests
from lemgendary-env-manager or lemgendary-training-suite.
"""

from typing import Any

from .base import make_code_cell


def build_install_cell(target: str = "kaggle") -> dict[str, Any]:
    """Build the dependency installation and hardware probe code cell."""
    if target == "kaggle":
        source = [
            "import os, sys, subprocess, platform, shutil\n",
            "print('[ENV] Probing hardware accelerator...')\n",
            "\n",
            "torch_index = 'https://download.pytorch.org/whl/cpu'\n",
            "accel_type = 'cpu'\n",
            "if shutil.which('nvidia-smi'):\n",
            "    torch_index = 'https://download.pytorch.org/whl/cu121'\n",
            "    accel_type = 'cuda_cu121'\n",
            "elif shutil.which('rocm-smi'):\n",
            "    torch_index = 'https://download.pytorch.org/whl/rocm6.1'\n",
            "    accel_type = 'rocm6.1'\n",
            "else:\n",
            "    try:\n",
            "        import torch\n",
            "        if torch.cuda.is_available():\n",
            "            v = torch.version.cuda or ''\n",
            "            parts = v.split('.')[:2]\n",
            "            cuda_tag = 'cu' + ''.join(parts)\n",
            "            torch_index = f'https://download.pytorch.org/whl/{cuda_tag}'\n",
            "            accel_type = f'cuda_{cuda_tag}'\n",
            "        elif hasattr(torch, 'version') and hasattr(torch.version, 'hip') and torch.version.hip:\n",
            "            v = torch.version.hip or ''\n",
            "            parts = v.split('.')[:2]\n",
            "            rocm_tag = 'rocm' + '.'.join(parts)\n",
            "            torch_index = f'https://download.pytorch.org/whl/{rocm_tag}'\n",
            "            accel_type = f'rocm_{rocm_tag}'\n",
            "    except ImportError:\n",
            "        pass\n",
            "\n",
            "if accel_type == 'cpu' and platform.system() == 'Windows':\n",
            "    torch_index = 'https://download.pytorch.org/whl/cpu'\n",
            "    accel_type = 'directml'\n",
            "\n",
            "print(f'[ENV] Accelerator: {accel_type}')\n",
            "print(f'[ENV] PyTorch index: {torch_index}')\n",
            "\n",
            "req_candidates = [\n",
            "    '/kaggle/working/lemgendary-env-manager/requirements/requirements-training.txt',\n",
            "    '/kaggle/working/lemgendary-env-manager/requirements/lemgendary-training-suite.requirements.txt',\n",
            "    '/kaggle/working/lemgendary-training-suite/requirements.txt',\n",
            "    '/kaggle/working/model-training/lemgendary-training-suite/requirements.txt',\n",
            "]\n",
            "req_path = next((p for p in req_candidates if os.path.exists(p)), None)\n",
            "\n",
            "if req_path:\n",
            "    print(f'[ENV] Manifest: {req_path}')\n",
            "    res = subprocess.run(\n",
            "        [sys.executable, '-m', 'pip', 'install', '-q',\n",
            "         '--extra-index-url', torch_index,\n",
            "         '--upgrade-strategy', 'only-if-needed',\n",
            "         '-r', req_path],\n",
            "        capture_output=True, text=True)\n",
            "    if res.returncode == 0:\n",
            "        print('[OK] Environment Ready.')\n",
            "        try:\n",
            "            import importlib; importlib.invalidate_caches()\n",
            "            import torch as _t\n",
            "            dev = 'CUDA ' + _t.version.cuda if _t.cuda.is_available() else 'CPU'\n",
            "            print(f'[OK] torch {_t.__version__} on {dev}')\n",
            "        except Exception:\n",
            "            pass\n",
            "    else:\n",
            "        print('[WARNING] Dependency installation finished with non-zero exit code.')\n",
            "        if res.stderr:\n",
            "            print(res.stderr[-2000:])\n",
            "else:\n",
            "    print('[ERROR] Could not open requirements file: No such file or directory')\n",
            "    print(\"[REMEDY] Ensure 'requirements.txt' exists in the root of the repository.\")\n",
            "    print('[ACTION REQUIRED] Suite clone failed in Step 3 because SUITE_PAT/GITHUB_PAT is missing from Kaggle Secrets.')\n",
            "    print('[ACTION REQUIRED] Fix: Go to Kaggle Notebook top bar -> Add-ons -> Secrets -> Add SUITE_PAT or GITHUB_PAT with your GitHub token.')\n",
        ]
    else:
        source = [
            "import os, sys, subprocess, platform, shutil\n",
            "print('[ENV] Probing hardware accelerator...')\n",
            "\n",
            "torch_index = 'https://download.pytorch.org/whl/cpu'\n",
            "accel_type = 'cpu'\n",
            "if shutil.which('nvidia-smi'):\n",
            "    torch_index = 'https://download.pytorch.org/whl/cu121'\n",
            "    accel_type = 'cuda_cu121'\n",
            "elif shutil.which('rocm-smi'):\n",
            "    torch_index = 'https://download.pytorch.org/whl/rocm6.1'\n",
            "    accel_type = 'rocm6.1'\n",
            "else:\n",
            "    try:\n",
            "        import torch\n",
            "        if torch.cuda.is_available():\n",
            "            v = torch.version.cuda or ''\n",
            "            parts = v.split('.')[:2]\n",
            "            cuda_tag = 'cu' + ''.join(parts)\n",
            "            torch_index = f'https://download.pytorch.org/whl/{cuda_tag}'\n",
            "            accel_type = f'cuda_{cuda_tag}'\n",
            "        elif hasattr(torch, 'version') and hasattr(torch.version, 'hip') and torch.version.hip:\n",
            "            v = torch.version.hip or ''\n",
            "            parts = v.split('.')[:2]\n",
            "            rocm_tag = 'rocm' + '.'.join(parts)\n",
            "            torch_index = f'https://download.pytorch.org/whl/{rocm_tag}'\n",
            "            accel_type = f'rocm_{rocm_tag}'\n",
            "    except ImportError:\n",
            "        pass\n",
            "\n",
            "print(f'[ENV] Accelerator: {accel_type}')\n",
            "print(f'[ENV] PyTorch index: {torch_index}')\n",
            "\n",
            "req_candidates = [\n",
            "    '/content/lemgendary-env-manager/requirements/requirements-training.txt',\n",
            "    '/content/lemgendary-env-manager/requirements/lemgendary-training-suite.requirements.txt',\n",
            "    '/content/lemgendary-training-suite/requirements.txt',\n",
            "    '/content/model-training/lemgendary-training-suite/requirements.txt',\n",
            "]\n",
            "req_path = next((p for p in req_candidates if os.path.exists(p)), None)\n",
            "\n",
            "if req_path:\n",
            "    print(f'[ENV] Manifest: {req_path}')\n",
            "    res = subprocess.run(\n",
            "        [sys.executable, '-m', 'pip', 'install', '-q',\n",
            "         '--extra-index-url', torch_index,\n",
            "         '--upgrade-strategy', 'only-if-needed',\n",
            "         '-r', req_path],\n",
            "        capture_output=True, text=True)\n",
            "    if res.returncode == 0:\n",
            "        print('[OK] Environment Ready.')\n",
            "        try:\n",
            "            import importlib; importlib.invalidate_caches()\n",
            "            import torch as _t\n",
            "            dev = 'CUDA ' + _t.version.cuda if _t.cuda.is_available() else 'CPU'\n",
            "            print(f'[OK] torch {_t.__version__} on {dev}')\n",
            "        except Exception:\n",
            "            pass\n",
            "    else:\n",
            "        print('[WARNING] Dependency installation finished with non-zero exit code.')\n",
            "        if res.stderr:\n",
            "            print(res.stderr[-2000:])\n",
            "else:\n",
            "    print('[ERROR] Could not open requirements file: No such file or directory')\n",
            "    print(\"[REMEDY] Ensure 'requirements.txt' exists in the root of the repository.\")\n",
            "    print('[ACTION REQUIRED] Suite clone failed in Step 3 because SUITE_PAT/GITHUB_PAT is missing from Colab Secrets.')\n",
            "    print('[ACTION REQUIRED] Fix: Go to Colab Secrets and add SUITE_PAT or GITHUB_PAT with your GitHub token.')\n",
        ]

    return make_code_cell(source)
