"""Model hub preparation, weight recovery, and checkpoint hydration cell generator.

Initializes model manifolds in LemGendaryModels and searches KaggleHub / Google Drive
for prior checkpoints and metrics histories.
"""

from typing import Any

from ..registry import ModelNotebookMeta
from .base import make_code_cell


def build_hub_prep_cell(meta: ModelNotebookMeta, target: str = "kaggle") -> dict[str, Any]:
    """Build the model hub structure initialization code cell."""
    hub_root = "/kaggle/working/LemGendaryModels" if target == "kaggle" else "/content/LemGendaryModels"
    source = [
        "import os\n",
        f"hub_root = '{hub_root}'\n",
        f"model_key = '{meta.model_key}'\n",
        "model_dir = os.path.join(hub_root, model_key)\n",
        "ckpt_dir = os.path.join(model_dir, 'checkpoints')\n",
        "\n",
        "print(f'[HUB] Initializing Lean Manifold for {model_key}...')\n",
        "os.makedirs(ckpt_dir, exist_ok=True)\n",
        "print(f'[OK] Manifold structure ready at {model_dir}')\n",
    ]
    return make_code_cell(source)


def build_checkpoint_recovery_cell(meta: ModelNotebookMeta, target: str = "kaggle") -> dict[str, Any]:
    """Build the deep checkpoint and metrics recovery code cell."""
    if target == "kaggle":
        source = [
            "import os, shutil\n",
            f"model_key = '{meta.model_key}'\n",
            "print(f'[RECOVERY] Deep-searching for {model_key} checkpoints...')\n",
            "hub_root = '/kaggle/working/LemGendaryModels'\n",
            "model_hub_dir = os.path.join(hub_root, model_key)\n",
            "ckpt_hub_dir = os.path.join(model_hub_dir, 'checkpoints')\n",
            "os.makedirs(ckpt_hub_dir, exist_ok=True)\n",
            "\n",
            "reg_filename = ''\n",
            "try:\n",
            "    import yaml\n",
            "    yaml_path = '/kaggle/working/lemgendary-training-suite/unified_models_v2.yaml'\n",
            "    if os.path.exists(yaml_path):\n",
            "        with open(yaml_path, 'r') as f: reg = yaml.safe_load(f)\n",
            "        reg_filename = reg.get(model_key, {}).get('filename', '')\n",
            "except Exception as e: print(f'[REMEDY] An error occurred during environment setup: {e}')\n",
            "\n",
            "target_slugs = [model_key.lower().replace('_', ''), model_key.lower().replace('_', '-'), reg_filename.lower() if reg_filename else '']\n",
            "target_slugs = [s for s in target_slugs if s]\n",
            "\n",
            "found_ckpts = []\n",
            "try:\n",
            "    import kagglehub\n",
            f"    kh_dl = kagglehub.model_download('{meta.k_handle}')\n",
            "    if kh_dl and os.path.exists(kh_dl):\n",
            "        print(f'   -> [KAGGLEHUB] Dynamic latest model version resolved: {kh_dl}')\n",
            "        for root_d, _, files in os.walk(kh_dl):\n",
            "            for f in files:\n",
            "                if f.lower().endswith(('.pth', '.pt')) and (any(slug in f.lower() for slug in target_slugs) or 'best' in f.lower() or 'latest' in f.lower() or 'progress' in f.lower()):\n",
            "                    found_ckpts.append(os.path.join(root_d, f))\n",
            "except Exception as kh_e: pass\n",
            "\n",
            "if os.path.exists('/kaggle/input'):\n",
            "    try:\n",
            "        queue = ['/kaggle/input']\n",
            "        depths = {'/kaggle/input': 0}\n",
            "        while queue:\n",
            "            curr = queue.pop(0)\n",
            "            depth = depths[curr]\n",
            "            if depth > 7: continue\n",
            "            for item in os.listdir(curr):\n",
            "                path = os.path.join(curr, item)\n",
            "                if os.path.isdir(path):\n",
            "                    item_lower = item.lower()\n",
            "                    if item_lower in ['datasets', 'images', 'train', 'val', 'test', 'validation', 'dataset']:\n",
            "                        continue\n",
            "                    depths[path] = depth + 1\n",
            "                    queue.append(path)\n",
            "                    \n",
            "                    if any(slug in item_lower for slug in target_slugs) or 'checkpoint' in item_lower or 'weights' in item_lower or 'models' in item_lower:\n",
            "                        try:\n",
            "                            for f in os.listdir(path):\n",
            "                                if f.lower().endswith('.pth') and (any(slug in f.lower() for slug in target_slugs) or 'best' in f.lower() or 'latest' in f.lower() or 'progress' in f.lower()):\n",
            "                                    found_ckpts.append(os.path.join(path, f))\n",
            "                        except:\n",
            "                            pass\n",
            "    except Exception:\n",
            "        pass\n",
            "\n",
            "found_ckpts = sorted(list(set(found_ckpts)))\n",
            "if found_ckpts:\n",
            "    print(f'   -> [FOUND] {len(found_ckpts)} binaries in Kaggle Manifold.')\n",
            "    for src in found_ckpts:\n",
            "        if f'/{model_key}/' not in src.replace('\\\\', '/') and f'{model_key}' not in os.path.basename(src):\n",
            "            continue\n",
            "        if not os.path.exists(src):\n",
            "            print(f'   -> [WARNING] Source missing (Ghost File/Broken Link): {src}')\n",
            "            continue\n",
            "        fname = os.path.basename(src)\n",
            "        target_f = fname\n",
            "        if 'latest' in fname.lower(): target_f = f'{model_key}_latest.pth'\n",
            "        elif 'best' in fname.lower(): target_f = f'{model_key}_best.pth'\n",
            "        elif 'progress' in fname.lower(): target_f = f'{model_key}_progress.pth'\n",
            "        \n",
            "        dst = os.path.join(ckpt_hub_dir, target_f)\n",
            "        if not os.path.exists(dst) or os.path.getsize(src) > os.path.getsize(dst):\n",
            "            shutil.copy2(src, dst)\n",
            "            print(f'   -> [OK] Recovered: {fname} -> {target_f}')\n",
            "    \n",
            "    metrics_found = False\n",
            "    for src in found_ckpts:\n",
            "        for d in [os.path.dirname(os.path.dirname(src)), os.path.dirname(src)]:\n",
            "            m_path = os.path.join(d, 'metrics.csv')\n",
            "            if os.path.exists(m_path):\n",
            "                try:\n",
            "                    shutil.copy2(m_path, os.path.join(model_hub_dir, 'metrics.csv'))\n",
            "                    print(f'[METRICS] Recovered metrics.csv from {os.path.basename(d)}')\n",
            "                    metrics_found = True; break\n",
            "                except Exception as e: print(f'[REMEDY] An error occurred during environment setup: {e}')\n",
            "        if metrics_found: break\n",
            "else: print('   -> [SKIP] No existing checkpoints found in Kaggle Inputs manifold.')\n",
        ]
    else:
        source = [
            "import os, shutil\n",
            f"model_key = '{meta.model_key}'\n",
            "print(f'[RECOVERY] Deep-searching for {model_key} checkpoints...')\n",
            "hub_root = '/content/LemGendaryModels'\n",
            "model_hub_dir = os.path.join(hub_root, model_key)\n",
            "ckpt_hub_dir = os.path.join(model_hub_dir, 'checkpoints')\n",
            "os.makedirs(ckpt_hub_dir, exist_ok=True)\n",
            "\n",
            "reg_filename = ''\n",
            "try:\n",
            "    import yaml\n",
            "    yaml_path = '/content/lemgendary-training-suite/unified_models_v2.yaml'\n",
            "    if os.path.exists(yaml_path):\n",
            "        with open(yaml_path, 'r') as f: reg = yaml.safe_load(f)\n",
            "        reg_filename = reg.get(model_key, {}).get('filename', '')\n",
            "except Exception as e: print(f'[REMEDY] An error occurred during environment setup: {e}')\n",
            "\n",
            "target_slugs = [model_key.lower().replace('_', ''), model_key.lower().replace('_', '-'), reg_filename.lower() if reg_filename else '']\n",
            "target_slugs = [s for s in target_slugs if s]\n",
            "\n",
            "found_ckpts = []\n",
            "if os.path.exists('/content/drive/MyDrive'):\n",
            "    try:\n",
            "        queue = ['/content/drive/MyDrive']\n",
            "        depths = {'/content/drive/MyDrive': 0}\n",
            "        while queue:\n",
            "            curr = queue.pop(0)\n",
            "            depth = depths[curr]\n",
            "            if depth > 7: continue\n",
            "            for item in os.listdir(curr):\n",
            "                path = os.path.join(curr, item)\n",
            "                if os.path.isdir(path):\n",
            "                    item_lower = item.lower()\n",
            "                    if item_lower in ['datasets', 'images', 'train', 'val', 'test', 'validation', 'dataset']:\n",
            "                        continue\n",
            "                    depths[path] = depth + 1\n",
            "                    queue.append(path)\n",
            "                    \n",
            "                    if any(slug in item_lower for slug in target_slugs) or 'checkpoint' in item_lower or 'weights' in item_lower or 'models' in item_lower:\n",
            "                        try:\n",
            "                            for f in os.listdir(path):\n",
            "                                if f.lower().endswith('.pth') and (any(slug in f.lower() for slug in target_slugs) or 'best' in f.lower() or 'latest' in f.lower() or 'progress' in f.lower()):\n",
            "                                    found_ckpts.append(os.path.join(path, f))\n",
            "                        except:\n",
            "                            pass\n",
            "    except Exception:\n",
            "        pass\n",
            "\n",
            "found_ckpts = sorted(list(set(found_ckpts)))\n",
            "if found_ckpts:\n",
            "    print(f'   -> [FOUND] {len(found_ckpts)} binaries in Google Drive.')\n",
            "    for src in found_ckpts:\n",
            "        if f'/{model_key}/' not in src.replace('\\\\', '/') and f'{model_key}' not in os.path.basename(src):\n",
            "            continue\n",
            "        if not os.path.exists(src):\n",
            "            print(f'   -> [WARNING] Source missing (Ghost File/Broken Link): {src}')\n",
            "            continue\n",
            "        fname = os.path.basename(src)\n",
            "        target_f = fname\n",
            "        if 'latest' in fname.lower(): target_f = f'{model_key}_latest.pth'\n",
            "        elif 'best' in fname.lower(): target_f = f'{model_key}_best.pth'\n",
            "        elif 'progress' in fname.lower(): target_f = f'{model_key}_progress.pth'\n",
            "        \n",
            "        dst = os.path.join(ckpt_hub_dir, target_f)\n",
            "        if not os.path.exists(dst) or os.path.getsize(src) > os.path.getsize(dst):\n",
            "            shutil.copy2(src, dst)\n",
            "            print(f'   -> [OK] Recovered: {fname} -> {target_f}')\n",
            "    \n",
            "    metrics_found = False\n",
            "    for src in found_ckpts:\n",
            "        for d in [os.path.dirname(os.path.dirname(src)), os.path.dirname(src)]:\n",
            "            m_path = os.path.join(d, 'metrics.csv')\n",
            "            if os.path.exists(m_path):\n",
            "                try:\n",
            "                    shutil.copy2(m_path, os.path.join(model_hub_dir, 'metrics.csv'))\n",
            "                    print(f'[METRICS] Recovered metrics.csv from {os.path.basename(d)}')\n",
            "                    metrics_found = True; break\n",
            "                except Exception as e: print(f'[REMEDY] An error occurred during environment setup: {e}')\n",
            "        if metrics_found: break\n",
            "else: print('   -> [SKIP] No existing checkpoints found in Google Drive manifold.')\n",
        ]

    return make_code_cell(source)


def build_stealth_cell(meta: ModelNotebookMeta, target: str = "kaggle") -> dict[str, Any]:
    """Build the stealth model loading and hydration code cell."""
    hub_root = "/kaggle/working/LemGendaryModels" if target == "kaggle" else "/content/LemGendaryModels"
    source = [
        "import os, base64, torch, shutil\n",
        f"model_key = '{meta.model_key}'\n",
        f"hub_root = '{hub_root}'\n",
        "model_hub_dir = os.path.join(hub_root, model_key)\n",
        "ckpt_hub_dir = os.path.join(model_hub_dir, 'checkpoints')\n",
        "os.makedirs(ckpt_hub_dir, exist_ok=True)\n",
        "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
        "\n",
        "input_ckpts = []\n",
        "if os.path.exists('/kaggle/input'):\n",
        "    try:\n",
        "        queue = ['/kaggle/input']\n",
        "        depths = {'/kaggle/input': 0}\n",
        "        while queue:\n",
        "            curr = queue.pop(0)\n",
        "            depth = depths[curr]\n",
        "            if depth > 6: continue\n",
        "            for item in os.listdir(curr):\n",
        "                path = os.path.join(curr, item)\n",
        "                if os.path.isdir(path):\n",
        "                    item_lower = item.lower()\n",
        "                    if item_lower in ['datasets', 'images', 'train', 'val', 'test', 'validation', 'dataset']:\n",
        "                        continue\n",
        "                    depths[path] = depth + 1\n",
        "                    queue.append(path)\n",
        "                    \n",
        f"                    if 'checkpoints' in item_lower or 'models' in item_lower or 'weights' in item_lower or model_key.replace('_', '') in item_lower.replace('_', ''):\n",
        "                        try:\n",
        "                            for f in os.listdir(path):\n",
        f"                                if f.lower().endswith('.pth') and any(x in f.lower() for x in [model_key.lower().replace('_', ''), 'best', 'latest']):\n",
        "                                    input_ckpts.append(os.path.join(path, f))\n",
        "                        except:\n",
        "                            pass\n",
        "    except Exception:\n",
        "        pass\n",
        "\n",
        "if input_ckpts:\n",
        "    print(f'[RECOVERY] Hydrating hub from Kaggle Inputs...')\n",
        "    for src in input_ckpts:\n",
        "        fname = os.path.basename(src)\n",
        "        dst = os.path.join(ckpt_hub_dir, fname)\n",
        "        if not os.path.exists(dst) or os.path.getsize(src) > os.path.getsize(dst):\n",
        "            shutil.copy2(src, dst)\n",
        "            print(f'   -> [OK] Recovered {fname}')\n",
        "\n",
        "    src_met = None\n",
        "    if os.path.exists('/kaggle/input'):\n",
        "        try:\n",
        "            queue = ['/kaggle/input']\n",
        "            depths = {'/kaggle/input': 0}\n",
        "            while queue:\n",
        "                curr = queue.pop(0)\n",
        "                depth = depths[curr]\n",
        "                if depth > 6: continue\n",
        "                for item in os.listdir(curr):\n",
        "                    path = os.path.join(curr, item)\n",
        "                    if os.path.isdir(path):\n",
        "                        item_lower = item.lower()\n",
        "                        if item_lower in ['images', 'train', 'val', 'test']:\n",
        "                            continue\n",
        "                        depths[path] = depth + 1\n",
        "                        queue.append(path)\n",
        "                    elif item == 'metrics.csv':\n",
        "                        src_met = path\n",
        "                        break\n",
        "                if src_met: break\n",
        "        except Exception as e: print(f'[REMEDY] An error occurred during environment setup: {e}')\n",
        "        \n",
        "    if src_met:\n",
        "        dst_met = os.path.join(model_hub_dir, 'metrics.csv')\n",
        "        if not os.path.exists(dst_met) or os.path.getsize(src_met) > os.path.getsize(dst_met):\n",
        "            shutil.copy2(src_met, dst_met)\n",
        "            print(f'[OK] [RECOVERY] Hydrated metrics.csv from {os.path.basename(os.path.dirname(src_met))}')\n",
        "\n",
        "    import glob\n",
        f"    search_paths = [p for p in glob.glob(os.path.join(ckpt_hub_dir, '*.pth')) if any(x in os.path.basename(p) for x in [model_key, model_key.replace('_', '-')])]\n",
        "    search_paths.sort(key=lambda x: (0 if 'best' in x else 1 if 'latest' in x else 2, -os.path.getsize(x)))\n",
        "    found = []\n",
        "    for p in search_paths: \n",
        "        if os.path.exists(p) and os.path.getsize(p) > 10 * 1024 * 1024:\n",
        "            found.append(p)\n",
        "\n",
        "    model_path = found[0] if found else None\n",
        "    if model_path:\n",
        "        print(f'[SOTA] Loading pre-trained weights: {model_path}')\n",
        "        ckpt = torch.load(model_path, map_location=device, weights_only=False)\n",
        "        print(f'[OK] Weights anchored on {device}.')\n",
        "    else: print('[WARNING] No existing weights found. Starting from scratch.')\n",
    ]
    return make_code_cell(source)
